# Generated by Django 3.1.2 on 2021-05-15 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='brend_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=256, unique=True, verbose_name='Название бренда')),
                ('del_status', models.BooleanField(default=True, verbose_name='Статус удаления')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'db_table': 'brends',
            },
        ),
        migrations.CreateModel(
            name='category_preporat_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=256, unique=True, verbose_name='Название категории')),
                ('del_status', models.BooleanField(default=True, verbose_name='Статус удаления')),
            ],
            options={
                'verbose_name': 'Категория препората',
                'verbose_name_plural': 'Категории препоратов',
                'db_table': 'category_preporat',
            },
        ),
        migrations.CreateModel(
            name='county_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=256, unique=True, verbose_name='Название страны')),
                ('del_status', models.BooleanField(default=True, verbose_name='Статус удаления')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='pod_category_preporat_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=256, unique=True, verbose_name='Название подкатегории')),
                ('del_status', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('category_preporat_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category_preporat_list', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория препората',
                'verbose_name_plural': 'Подкатегории препоратов',
                'db_table': 'pod_category_preporat',
            },
        ),
        migrations.CreateModel(
            name='postavchiki_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=256, verbose_name='Название поставщика')),
                ('addres', models.TextField(default=None, verbose_name='Адрес поставщика')),
                ('phone', models.CharField(max_length=32, null=True, verbose_name='Телефон поставщика')),
                ('del_status', models.BooleanField(default=True, verbose_name='Статус удаления')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'db_table': 'postavchiki',
            },
        ),
        migrations.CreateModel(
            name='preporat_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=256, verbose_name='Название препората')),
                ('buy_price', models.FloatField(default=0, verbose_name='Цена закупочная')),
                ('sell_price', models.FloatField(default=0, verbose_name='Цена реализации')),
                ('recept', models.BooleanField(default=False, verbose_name='Требование рецепта')),
                ('count', models.IntegerField(default=0, verbose_name='Кол-во препората в наличии')),
                ('del_status', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('brend_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.brend_list', verbose_name='Брэнд')),
                ('pod_category_preporat_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.pod_category_preporat_list', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Препорат',
                'verbose_name_plural': 'Препораты',
                'db_table': 'preporats',
            },
        ),
        migrations.CreateModel(
            name='sell_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=None, verbose_name='Дата и время продажи')),
                ('total_price', models.FloatField(default=0, verbose_name='Итоговая стоимость')),
                ('total_count', models.IntegerField(default=0, verbose_name='Итоговое количество')),
                ('del_status', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('sell_user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'db_table': 'sell',
            },
        ),
        migrations.CreateModel(
            name='sell_element_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=None, verbose_name='Дата и время продажи')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('del_status', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('preporat_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.preporat_list', verbose_name='Препорат')),
                ('sell_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Продажа элемент',
                'verbose_name_plural': 'Продажи элементы',
                'db_table': 'sell_element',
            },
        ),
        migrations.CreateModel(
            name='proizvoditel_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=256, unique=True, verbose_name='Название производителя')),
                ('address', models.TextField(default=None, verbose_name='Адрес производителя')),
                ('del_status', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('country_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.county_list', verbose_name='Страна производителя')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'db_table': 'proizvoditels',
            },
        ),
        migrations.AddField(
            model_name='preporat_list',
            name='proizvoditel_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.proizvoditel_list', verbose_name='Производитель'),
        ),
        migrations.CreateModel(
            name='postavki_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=None, verbose_name='Дата и время поставки')),
                ('total_price', models.FloatField(default=0, verbose_name='Итоговая стоимость')),
                ('total_count', models.IntegerField(default=0, verbose_name='Общее кол-во товаров')),
                ('status_postavki', models.BooleanField(default=True, verbose_name='Статус выполнения поставки')),
                ('del_status', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('postavchiki_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.postavchiki_list', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
                'db_table': 'postavki',
            },
        ),
        migrations.CreateModel(
            name='postavki_element_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postavka_price', models.FloatField(default=0, verbose_name='Закупочная стоимость')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('del_status', models.BooleanField(default=True, verbose_name='Статус удаления')),
                ('postavki_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.postavki_list', verbose_name='Поставка')),
                ('preporat_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.preporat_list', verbose_name='Препорат')),
            ],
            options={
                'verbose_name': 'Поставки товар',
                'verbose_name_plural': 'Поставки товары',
                'db_table': 'postavki_element',
            },
        ),
    ]
