# Generated by Django 3.1.2 on 2021-05-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_proizvoditel_list_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='proizvoditel_list',
            name='zavod_name',
            field=models.CharField(default=None, max_length=256, verbose_name='Завод-производитель'),
        ),
    ]
