# Generated by Django 3.1.2 on 2021-05-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_proizvoditel_list_zavod_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_element_list',
            name='price',
            field=models.FloatField(default=0, verbose_name='Итоговая стоимость'),
        ),
    ]
