# Generated by Django 3.1.2 on 2021-05-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_sell_element_list_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preporat_list',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='preporat_list',
            name='sell_price',
        ),
        migrations.AddField(
            model_name='preporat_list',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
    ]
