# Generated by Django 3.1.2 on 2021-05-15 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210515_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postavchiki_list',
            old_name='addres',
            new_name='address',
        ),
    ]
