# Generated by Django 3.1.2 on 2021-05-15 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210515_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell_element_list',
            name='sell_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.sell_list', verbose_name='Продажа'),
        ),
    ]
