# Generated by Django 3.1.2 on 2021-05-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_sell_element_list_sell_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postavki_list',
            name='date_time',
        ),
        migrations.AddField(
            model_name='postavki_list',
            name='date',
            field=models.DateTimeField(default=None, verbose_name='Дата поставки'),
        ),
    ]
