# Generated by Django 3.1.2 on 2021-05-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210516_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postavki_list',
            name='date',
            field=models.DateField(default=None, verbose_name='Дата поставки'),
        ),
    ]
