# Generated by Django 3.1.2 on 2021-05-16 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210516_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postavki_list',
            old_name='date',
            new_name='date_postavki',
        ),
    ]
