# Generated by Django 3.1.2 on 2021-05-10 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('add_user', 'Добавление сотрудника'), ('edit_user', 'Редактирвоание сотрудника'), ('delete_user', 'Удаление сотрудника')), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
