# Generated by Django 3.1.2 on 2021-05-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20210511_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=32, null=True, verbose_name='Телефон'),
        ),
    ]
